language: node_js

# sudo: false

node_js:
  - "4"
  - "6"
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - "npm run build"

script:
  - "npm run coverage"

after_success:
  - "npm install -g codeclimate-test-reporter"
  - "CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info"
